name: Generate Snake Animation

on:
  schedule: # runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # allows you to run it manually
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: kimhongzhang323
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
